site_name: Erstsemesterakademie BaWü zukunftsfähig - Digitale Umsetzung
site_url: https://help.ersti-akademie-bw.de
repo_url: https://github.com/davidkopp/ersti-akademie-help
nav:
    - Start: index.md
    - BigBlueButton:
        Allgemeines: bbb.md
        Verbindungsaufbau zur Konferenz: bbb-verbindung.md
        Benutzungsoberfläche: bbb-benutzung.md
theme:
    name: material
    language: de
    palette:
        primary: green
        accent: green
    features:
      - navigation.tabs
      - toc.autohide
markdown_extensions:
    - admonition
    - pymdownx.critic
    - pymdownx.betterem:
        smart_enable: all
